#!/usr/bin/env python3
"""
Export the key AIME prompt templates into Python modules for easier inspection.

Outputs two files in ../generated/ :
- aime_prompt_templates.py (o4/gpt-4.1 pipeline)
- aime_2p5_prompt_templates.py (Gemini 2.5 self-reflection pipeline)
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Dict

import sys

ARC_MEMO_ROOT = Path(__file__).resolve().parents[3] / "arc_memo"
if str(ARC_MEMO_ROOT) not in sys.path:
    sys.path.insert(0, str(ARC_MEMO_ROOT))

try:
    from concept_mem.data.aime_simple_solver_v3 import (  # type: ignore  # noqa: E402
        AIME_SYSTEM_PROMPT,
        AIME_SOLVE_PROMPT,
        AIME_OUTPUT_REQUIREMENT,
    )
    from concept_mem.data.aime_thought_process import (  # type: ignore  # noqa: E402
        AIME_THOUGHT_PROCESS_TEMPLATE,
        REFLECTIVE_THOUGHT_PROCESS_TEMPLATE,
        REFLECTIVE_THOUGHT_PROCESS_TEMPLATE_MISTAKE_ONLY,
    )
    from concept_mem.abstraction.analysis_concept_prompts import (  # type: ignore  # noqa: E402
        EXTRACT_LESSON_FROM_AIME_FS_TEMPLATE_STRICT,
        EXTRACT_LESSON_FROM_AIME_FS_TEMPLATE_STRICT_UNCERTAIN,
        EXTRACT_LESSON_FROM_AIME_MISTAKE_TEMPLATE,
    )
    from concept_mem.data.aime_joint_solver import (  # type: ignore  # noqa: E402
        JOINT_SYSTEM_PROMPT,
        JOINT_PROMPT_TEMPLATE,
    )
    from concept_mem.data.aime_self_reflection import (  # type: ignore  # noqa: E402
        REFLECTION_SYSTEM_PROMPT,
        REFLECTION_PROMPT_TEMPLATE,
    )
    from concept_mem.selection.description.select import (  # type: ignore  # noqa: E402
        AIME_RET_TOPK_CONCEPT_TEMPLATE,
    )
except ModuleNotFoundError as exc:
    if exc.name == "llmplus":
        raise SystemExit(
            "Unable to import llmplus. Activate the arc_memo virtualenv before running this script."
        ) from exc
    raise

OUTPUT_DIR = Path(__file__).resolve().parents[1] / "generated"
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)


def escape_triple_quotes(text: str) -> str:
    escaped = text.replace("\\", "\\\\")
    return escaped.replace('"""', '\\"""')


def write_module(path: Path, sections: Dict[str, Dict[str, str]]) -> None:
    with path.open("w", encoding="utf-8") as f:
        docstring = (
            '# Auto-generated by scripts/export_prompt_templates.py\n'
            '# Do not edit directly.\n\n'
        )
        f.write(docstring)
        for heading, prompts in sections.items():
            f.write(f"{heading}\n")
            for var_name, template in prompts.items():
                escaped = escape_triple_quotes(template)
                f.write(f'{var_name} = """{escaped}"""\n\n')


def main() -> None:
    standard_sections = {
        "# Stage 1 – Solver (o4-mini / Gemini baseline)": {
            "AIME_SYSTEM_PROMPT": AIME_SYSTEM_PROMPT,
            "AIME_SOLVE_PROMPT": AIME_SOLVE_PROMPT,
            "AIME_OUTPUT_REQUIREMENT": AIME_OUTPUT_REQUIREMENT,
        },
        "# Stage 2 – Thought Process Generation (o4-mini)": {
            "AIME_THOUGHT_PROCESS_TEMPLATE": AIME_THOUGHT_PROCESS_TEMPLATE,
            "REFLECTIVE_THOUGHT_PROCESS_TEMPLATE": REFLECTIVE_THOUGHT_PROCESS_TEMPLATE,
            "REFLECTIVE_THOUGHT_PROCESS_TEMPLATE_MISTAKE_ONLY": REFLECTIVE_THOUGHT_PROCESS_TEMPLATE_MISTAKE_ONLY,
        },
        "# Stage 3 – Lesson Abstraction (gpt-4.1)": {
            "EXTRACT_LESSON_FROM_AIME_FS_TEMPLATE_STRICT": EXTRACT_LESSON_FROM_AIME_FS_TEMPLATE_STRICT,
            "EXTRACT_LESSON_FROM_AIME_MISTAKE_TEMPLATE": EXTRACT_LESSON_FROM_AIME_MISTAKE_TEMPLATE,
        },
    }
    write_module(OUTPUT_DIR / "aime_prompt_templates.py", standard_sections)

    pipeline_2p5_sections = {
        "# Stage 1 – Joint Solve + Thought Process (Gemini 2.5)": {
            "JOINT_SYSTEM_PROMPT": JOINT_SYSTEM_PROMPT,
            "JOINT_PROMPT_TEMPLATE": JOINT_PROMPT_TEMPLATE,
        },
        "# Stage 2 – Self-Reflection (Gemini 2.5)": {
            "REFLECTION_SYSTEM_PROMPT": REFLECTION_SYSTEM_PROMPT,
            "REFLECTION_PROMPT_TEMPLATE": REFLECTION_PROMPT_TEMPLATE,
        },
        "# Stage 3 – Lesson Abstraction (Gemini 2.5)": {
            "EXTRACT_LESSON_FROM_AIME_FS_TEMPLATE_STRICT_UNCERTAIN": EXTRACT_LESSON_FROM_AIME_FS_TEMPLATE_STRICT_UNCERTAIN,
        },
        "# Stage 4 – Lesson Retrieval (Gemini 2.5)": {
            "AIME_RET_TOPK_CONCEPT_TEMPLATE_2P5": AIME_RET_TOPK_CONCEPT_TEMPLATE,
        },
        "# Stage 5 – Validation Solve (Gemini 2.5 with lessons)": {
            "AIME_SYSTEM_PROMPT_2P5": AIME_SYSTEM_PROMPT,
            "AIME_SOLVE_PROMPT_2P5": AIME_SOLVE_PROMPT,
            "AIME_OUTPUT_REQUIREMENT_2P5": AIME_OUTPUT_REQUIREMENT,
        },
        "# Stage 5 Baseline – Validation Solve (Gemini 2.5 no retrieval)": {
            "AIME_SYSTEM_PROMPT_BASELINE_2P5": AIME_SYSTEM_PROMPT,
            "AIME_SOLVE_PROMPT_BASELINE_2P5": AIME_SOLVE_PROMPT,
            "AIME_OUTPUT_REQUIREMENT_BASELINE_2P5": AIME_OUTPUT_REQUIREMENT,
        },
    }
    write_module(OUTPUT_DIR / "aime_2p5_prompt_templates.py", pipeline_2p5_sections)

    print("Generated prompt modules:")
    print(f" - {OUTPUT_DIR / 'aime_prompt_templates.py'}")
    print(f" - {OUTPUT_DIR / 'aime_2p5_prompt_templates.py'}")


if __name__ == "__main__":
    main()


